version: '3.2'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  database_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "olg-199774@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5000:80"
    volumes:
      - pga4data:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      - backend


networks:
  backend:
  frontend:
volumes:
  pgdata:
  pga4data:
